### ISSUE TITLE
Generated a password without numbers in them even if specified

### ISSUE THREAD

**Issue by suppagoddo** [brendanashworth/generate-password#19]
Used this as option:
let passwordOptions = {
        length: 15,
        numbers: true,
        symbols: true
};
and called "generator.generate(passwordOptions);"

It generated this password which does not have a number in it.

Generated Password: "q?xfnIaTdWlM?fD"

**Comment by brendanashworth** [comment]
@suppagoddo just passing the `numbers` flag *allows* numbers to be present in the password, it doesn't require them. To require at least one number to be present, you need to set the `strict` flag:

> `strict`: Boolean, password must include at least one character from each pool.

Like so:

```javascript
let passwordOptions = {
  length: 15,
  numbers: true,
  symbols: true,
  strict: true
};

generator.generate(passwordOptions);
```

**Comment by suppagoddo** [comment]
Cool. Thanks! Got it 👍
