### ISSUE TITLE
Does not work on Angular 4

### ISSUE THREAD

**Issue by xama5** [brendanashworth/generate-password#20]
I'm using Angular CLI to build an Angular 4 app and I can't get your package to work.

Angular CLI excludes the `crypto` library by default: https://github.com/angular/angular-cli/issues/1548#issuecomment-240962398
As your package depends on `crypto` (https://github.com/brendanashworth/generate-password/blob/master/src/generate.js#L1), it won't work. 
If I'm not mistaken, crypto is only required for this piece of code: https://github.com/brendanashworth/generate-password/blob/master/src/generate.js#L8

Wouldn't it make sense to replace that line with Math.random() (or similar), so it's compatible with Angular?

**Comment by brendanashworth** [comment]
Hi @xama5, thanks for opening an issue.

Would something like [`crypto-browserify`](https://github.com/crypto-browserify/crypto-browserify) work for you in this instance? I'm not an Angular CLI master, but it seems like it [uses `randombytes`](https://github.com/crypto-browserify/crypto-browserify/blob/acd878919d8be5b6d3f7678f1708a7afafa2319d/index.js#L3).

I wouldn't recommend replacing it with `Math.random()` as that's a pseudo-random number generator, and can't be trusted to create secure passwords.

**Comment by xama5** [comment]
Hey Brendan,

I just verified that `randombytes` instead of `crypto` does indeed work, so I opened a pull request.
Thank you very much for your hint! 👍
