### ISSUE TITLE
How to use this in Java ?

### ISSUE THREAD

**Issue by vishalbiradar** [brendanashworth/generate-password#22]
Hi, I am using this npm for my node project.
And I want to use it in my Java program also.
So how to use it in Java code ??
Please give tell me the steps and example.

**Comment by brendanashworth** [comment]
Hi @vishalbiradar ,
I'm glad you like the library. Unfortunately you won't be able to use it with Java as the JVM, afaik, doesn't offer bindings with v8 (what node.js uses). You'll need to find a Java-specific library that generates passwords.
