### ISSUE TITLE
Use in angular project

### ISSUE THREAD

**Issue by utpaul** [brendanashworth/generate-password#24]
Please update readme how can using angular and ionic project(examples)

**Comment by brendanashworth** [comment]
Hi @utpaul , I'm not very familiar with either of those projects so I don't know if I'll be able to help you. However if you're interested in learning or someone else knows how I'd be open to a PR.

**Comment by xama5** [comment]
@utpaul You can try to use this fork instead: https://github.com/xama5/generate-password-browser
More info: https://github.com/brendanashworth/generate-password/issues/25#issuecomment-383964851

I don't know if it'll work with Ionic. Try and see if it works.

**Comment by brendanashworth** [comment]
I'm going to go ahead and close this issue as there isn't really much to do here, besides maybe using the browser fork.
