### ISSUE TITLE
How to use this library on frontend side?

### ISSUE THREAD

**Issue by Photon79** [brendanashworth/generate-password#40]
I need to generate a password on the front-end side by the client request. How can I use this library?

**Comment by Aravin** [comment]
I have the same query.

I am not able to use this library with Angular 8.

**Comment by mt-ronkorving** [comment]
You can't, as it uses the Node.js `crypto` module.

**Comment by brendanashworth** [comment]
@Photon79  and @Aravin I'd encourage you to use this fork for browser support: https://github.com/oliver-la/generate-password-browser

At this time and probably the future I don't think we'll bring in native browser support to the core module.

**Comment by Aravin** [comment]
It is possible, long back I used this npm package to generate random password on web. This is the screenshot of my application.

![image](https://user-images.githubusercontent.com/4869265/79633926-26371900-8185-11ea-8ef0-e4405825e3d8.png)

I don't have that source code now. It is hosted here: https://www.epix.io/crypto/password-generator
