### ISSUE TITLE
some criteria do not work somethimes

### ISSUE THREAD

**Issue by noodle-lover** [brendanashworth/generate-password#41]
I just set the length of my password to be 6, include both cases, a special character and a number. But got a only a password without a special symbol. 

I'm sure this happens for password length less than six, but it shouldn't happen for 6 or more password lenght.

**Comment by brendanashworth** [comment]
Setting `symbols: true` only adds the _possibility_ of a special character being in the password; take a look at https://github.com/brendanashworth/generate-password/issues/36#issuecomment-579530876. If you want to make sure your password always includes a symbol and a number, set `strict` to `true`.

**Comment by mt-ronkorving** [comment]
@noodle-lover Maybe a good opportunity to make a PR to clarify the documentation in a way that would have made it clear to you.
