### ISSUE TITLE
Sometimes does not generate number into password

### ISSUE THREAD

**Issue by andredicioccio** [brendanashworth/generate-password#44]
Hi there,
I've noticed that sometimes when I generate passwords, even though I specify numbers: true, it does not add a number into the generated password.

For example when using:
```
    var password = generator.generate({
      length: 10,
      numbers: true
    });
    console.log(password);
```

I get this outcome (notice for example the second password generated has no number):

![image](https://user-images.githubusercontent.com/32121551/82826635-dd475280-9ef0-11ea-8c46-b53549dd0022.png)

**Comment by brendanashworth** [comment]
@andredicioccio , please take a look at a past issue for help on this:

> You should take a look at the `strict: true` flag, that will always include a lowercase and uppercase letter in passwords. This is not on by default.
> More info here: [#19 (comment)](https://github.com/brendanashworth/generate-password/issues/19#issuecomment-328235015)

Enabling the strict flag will solve this problem for you.
