### ISSUE TITLE
[bug] number is not always added to generated password

### ISSUE THREAD

**Issue by morficus** [brendanashworth/generate-password#46]
This is an intermittent bug. I suspect it has to do with using `numbers: true` in conjunction with `excludeSimilarCharacters: true`. It seems to fail about 30% of the times (using node v10) and 10% of the items (uising node v12) -- at least during my limited testing.

Here is some sample code to recreate the issue: https://runkit.com/embed/byemcgw0je47

And here is a screenshot showing a failure case:
![Screen Shot 2020-06-16 at 11 10 20 AM](https://user-images.githubusercontent.com/718799/84792824-59016000-afc2-11ea-8ff2-3a04e3f04d8c.png)

**Comment by Harshu53** [comment]
Use **strict: true** flag into generate function argument to follow all the pool given by you

**Comment by morficus** [comment]
closing this issue since using the `strict: true` flag solves this problem
(I missed that option in the documentation)
