### ISSUE TITLE
[Feature Request]: Shuffle character pool

### ISSUE THREAD

**Issue by SimonJang** [brendanashworth/generate-password#56]
I recently extended this package for use in a project. I've added character pool shuffling as an added layer of security ( or obscurity?) to make it even more nondeterministic in the password output.

Not sure what you think of it but if you're open for it, I can open a PR.

**Comment by brendanashworth** [comment]
So this in theory wouldn't change how nondeterministic the password output is in the typical case. In practice, the only time that this be of use is 1) a misspecified password generator that is not random and 2) when [`crypto.randomBytes`](https://github.com/brendanashworth/generate-password/blob/d95f213dd27a397f9e1db6f44f180421cef09eb1/src/generate.js#L13) is not truly random. Even in that case, this would only help a little bit against a targeted attack on this package.

I'm tempted to not vote for its inclusion, but is the pool shuffling a particularly small change? I don't see any negatives.

**Comment by SimonJang** [comment]
Hey @brendanashworth ,

Thanks for the response. I just posted it here as a suggestion. I follow your argumentation that the current implementation is just fine and character pool shuffling does not add an additional layer of security.

Thanks for your time!
