### ISSUE TITLE
Support named exports in node native ESM

### ISSUE THREAD

**Issue by perrin4869** [brendanashworth/generate-password#58]
Currently importing named exports from this module from an ESM module will error out:

```
❯ cat index.mjs
import { generate } from "generate-password";
❯ node index.mjs
file:///{...}/index.mjs:1
import { generate } from "generate-password";
         ^^^^^^^^
SyntaxError: Named export 'generate' not found. The requested module 'generate-password' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'generate-password';
const { generate } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

```

It would be nice to have support for this feature. This would require moving to a pure ESM module, or provide a CJS and an ESM build using rollup.

Edit: An additional alternative seems to be to not rename `exports` as `self` inside the module.
https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/

**Comment by joshua1** [comment]
This would be really nice to have

**Comment by brendanashworth** [comment]
This is really easy to add, I just don't know how to test that it works.

Any ideas, even manually?

**Comment by perrin4869** [comment]
Could test importing a module `test.mjs` like

```javascript
import { generate } from "generate-password";

export default generate();
```

Then test by doing something like `expect(import("test.mjs")).to.eventually.satisfy(...)`
Something along these lines would work i think!
