### ISSUE TITLE
Typescript definition for GenerateOptions.symbols is missing 'string' in Yarn package

### ISSUE THREAD

**Issue by theRealPadster** [brendanashworth/generate-password#59]
I'm not sure how this happened, but I installed the latest version of this package off [Yarn](https://yarnpkg.com/package/generate-password) and it says it's v1.6.0, but the typescript definition has the `symbols` option as just a boolean. It looks like this was fixed in Git a while ago. 

If I click "browse files" in the Yarn page sidebar, I can see the file [here](https://cdn.jsdelivr.net/npm/generate-password@1.6.0/src/generate.d.ts), without the 'string' type.

**Comment by gabzidevs** [comment]
#55 is still pending for release I think

**Comment by brendanashworth** [comment]
Thanks for the bump guys, just published 1.6.1 with the fix.
