### ISSUE TITLE
Despite lowercase and uppercase default are true no characters in the generated password

### ISSUE THREAD

**Issue by nemethyd** [brendanashworth/generate-password#60]
With the options:
{ length: 6, numbers: true, strict: false, symbols: true, exclude: '' }  the generated passwords never contain letters.
When the options are explicitly given:  {
  length: 6,
  numbers: true,
  strict: false,
  uppercase: true,
  symbols: true,
  exclude: ''
} the module works as expected

**Comment by bastiaan85** [comment]
Note the final option presented in the "Available options" in the documentation

> strict | Boolean, password must include at least one character from each pool. | false

As you have strict set to false, this requirement is not enabled and thus each pool remains optional for the end-result.

**Comment by brendanashworth** [comment]
@nemethyd it's not clear that the module is working incorrectly here, so I'm going to close this. Please reopen if you still think there's an issue.

Here's me using your options and getting a character:
```js
> gen.generate({ length: 6, numbers: true, strict: false, symbols: true, exclude: '' })
't82Kyo'
```
