### ISSUE TITLE
generate.js contains a reference to the missing dependency "crypto"

### ISSUE THREAD

**Issue by ducho** [brendanashworth/generate-password#65]
I try to use this package with webpack-encore but always module build failed to compile with errors.
```
Module build failed: Module not found:
"./node_modules/generate-password/src/generate.js" contains a reference to the file "crypto".
This file can not be found, please check it for typos or update it if the file got moved.
```

**Comment by brendanashworth** [comment]
@ducho did you try using the browser version here: https://github.com/oliver-la/generate-password-browser?

**Comment by johnleydelgado** [comment]
how did you solve this ? @ducho

**Comment by brendanashworth** [comment]
@johnleydelgado does generate-password-browser fix the problem for you? there isn't browser support in this repository
