### ISSUE TITLE
[DOC] Better to add about generate-password-browser in the readme

### ISSUE THREAD

**Issue by yadunandanbhat** [brendanashworth/generate-password#73]
As some people might want to run this in a browser environment, I think it would be better if we mentioned that this doesn't have browser support and instead use the forked project 'generate-password-browser'? would be helpful for beginners!

**Comment by brendanashworth** [comment]
That would be a good addition to the readme, do you want to submit a pull request?

**Comment by yadunandanbhat** [comment]
Yes, would love to!
