### ISSUE TITLE
Using a salt from a Python bcrypt library---"error - Error: Invalid salt version:"

### ISSUE THREAD

**Issue by chriscoindeskindices** [brendanashworth/generate-password#81]
I am using a salt generated by the Python 'bcrypt' library.  When trying to has a string with this salt, I receive an error message: 

error - Error: Invalid salt version: /g

Btw the salt I am using has a /g in it

**Comment by brendanashworth** [comment]
I don't think this is the right repo for this issue, we don't let you pass particular salts.
